# Generated by Django 4.1.1 on 2022-10-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_products',
            field=models.ManyToManyField(default=None, to='products.product'),
        ),
    ]
