# Generated by Django 4.1.1 on 2022-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0004_user_favourite_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourite_products',
            field=models.ManyToManyField(blank=True, default=None, to='products.product'),
        ),
    ]
