# Generated by Django 4.1.1 on 2022-09-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Good One', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no image', upload_to=''),
        ),
    ]
